// Mocks generated by Mockito 5.0.17 from annotations
// in firebasestarter/test/services/auth/sign_in_services/apple_sign_in_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:auth/auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sign_in_with_apple/sign_in_with_apple.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AppleCredentials].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleCredentials extends _i1.Mock implements _i2.AppleCredentials {
  MockAppleCredentials() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AuthorizationCredentialAppleID?> getAppleCredentials(
          {List<_i4.AppleIDAuthorizationScopes>? scopes, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAppleCredentials, [], {#scopes: scopes, #token: token}),
              returnValue: Future<_i4.AuthorizationCredentialAppleID?>.value())
          as _i3.Future<_i4.AuthorizationCredentialAppleID?>);
}

/// A class which mocks [AuthorizationCredentialAppleID].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAuthorizationCredentialAppleID extends _i1.Mock
    implements _i4.AuthorizationCredentialAppleID {
  MockAuthorizationCredentialAppleID() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get authorizationCode => (super
          .noSuchMethod(Invocation.getter(#authorizationCode), returnValue: '')
      as String);
}
