part of auth;

enum AuthError {
  INVALID_EMAIL,
  USER_DISABLED,
  USER_NOT_FOUND,
  WRONG_PASSWORD,
  EMAIL_ALREADY_IN_USE,
  INVALID_CREDENTIAL,
  OPERATION_NOT_ALLOWED,
  WEAK_PASSWORD,
  REQUIRES_RECENT_LOGIN,
  ERROR,
}
